# Generated by Django 5.0.2 on 2024-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('entrenamiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.TextField()),
                ('duracion', models.TextField()),
                ('calorias', models.IntegerField()),
            ],
        ),
    ]
