# Generated by Django 5.0.2 on 2024-03-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('ejercicio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('entrenamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.entrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('serie_id', models.AutoField(primary_key=True, serialize=False)),
                ('repeticiones', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.ejercicio')),
            ],
        ),
    ]
